version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/yeab_game_zone_db
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - CHAPA_API_KEY=${CHAPA_API_KEY}
      - WEBHOOK_URL=${WEBHOOK_URL}
    depends_on:
      - db
    command: sleep infinity

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=yeab_game_zone_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: